import os
import warnings
from pathlib import Path

from dotenv import load_dotenv
from platformdirs import user_cache_dir

PROJECT_ROOT = Path(__file__).resolve().parent.parent
print(f"PROJECT_ROOT: {PROJECT_ROOT}")

DOTENV_PATH = PROJECT_ROOT / ".env"
print(f"DOTENV_PATH: {DOTENV_PATH}")

# Load the .env file. load_dotenv() will search for .env in the current
# directory or parent directories. Explicitly providing the path is robust.
# It's safe to call this even if the file doesn't exist or is empty.
load_dotenv(dotenv_path=DOTENV_PATH)

# Disable Albumentations update
os.environ["NO_ALBUMENTATIONS_UPDATE"] = "1"

# ==== Load specific variables from the .env file ====

def raise_error_if_none(variable, variable_name):
    """Raises an error if the variable is None."""
    if variable is None:
        raise ValueError(f"Environment variable '{variable_name}' not set in the .env file.")

def raise_warning_if_none(variable, variable_name):
    """Raises a warning if the variable is None."""
    if variable is None:
        warnings.warn(
            f"Environment variable '{variable_name}' not set in the .env file.",
            UserWarning
        )

# -- Hugging Face Token --
HF_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
raise_warning_if_none(HF_TOKEN, "HUGGINGFACE_TOKEN")

# -- Workspace directory --
WORKSPACE_DIR = os.getenv("MEDVQA_WORKSPACE_DIR")
raise_error_if_none(WORKSPACE_DIR, "MEDVQA_WORKSPACE_DIR")

# -- Experiments directory --
EXPERIMENTS_DIR = os.path.join(WORKSPACE_DIR, 'experiments')

# -- Cache directories --
CACHE_DIR = os.path.join(WORKSPACE_DIR, 'cache')

# -- Fast / large-fast workspaces (optional; fall back to WORKSPACE_DIR) --
FAST_WORKSPACE_DIR = os.getenv('MEDVQA_FAST_WORKSPACE_DIR')
raise_warning_if_none(FAST_WORKSPACE_DIR, "MEDVQA_FAST_WORKSPACE_DIR")
if FAST_WORKSPACE_DIR is None:
    FAST_WORKSPACE_DIR = WORKSPACE_DIR

LARGE_FAST_WORKSPACE_DIR = os.getenv('MEDVQA_LARGE_FAST_WORKSPACE_DIR')
raise_warning_if_none(LARGE_FAST_WORKSPACE_DIR, "MEDVQA_LARGE_FAST_WORKSPACE_DIR")
if LARGE_FAST_WORKSPACE_DIR is None:
    LARGE_FAST_WORKSPACE_DIR = WORKSPACE_DIR

FAST_CACHE_DIR = os.path.join(FAST_WORKSPACE_DIR, 'cache')
LARGE_FAST_CACHE_DIR = os.path.join(LARGE_FAST_WORKSPACE_DIR, 'cache')

# -- Temporary directories --
TMP_DIR = os.path.join(WORKSPACE_DIR, 'tmp')
FAST_TMP_DIR = os.path.join(FAST_WORKSPACE_DIR, 'tmp')

# -- Results directory --
RESULTS_DIR = os.path.join(WORKSPACE_DIR, 'results')

# -- Regular expressions folder --
REGULAR_EXPRESSIONS_FOLDER = os.path.join(PROJECT_ROOT, 'medvqa', 'datasets', 'regular_expressions')

# -- Configs folder --
CONFIGS_FOLDER = os.path.join(PROJECT_ROOT, 'medvqa', 'configs')

# -- LLM prompts folder --
LLM_PROMPTS_DIR = os.path.join(PROJECT_ROOT, 'medvqa', 'prompts')

# -- YOLOv5 paths --
# NOTE: The following assumes that you have git cloned the YOLOv5 repo somewhere in your filesystem
# and have set the YOLOv5_PYTHON_PATH environment variable to an appropriate python executable.
# yolov5 is available at https://github.com/ultralytics/yolov5
YOLOv5_PYTHON_PATH = os.getenv('YOLOv5_PYTHON_PATH')
YOLOv5_TRAIN_SCRIPT_PATH = os.getenv('YOLOv5_TRAIN_SCRIPT_PATH')
YOLOv5_DETECT_SCRIPT_PATH = os.getenv('YOLOv5_DETECT_SCRIPT_PATH')
YOLOv5_RUNS_DETECT_DIR = os.getenv('YOLOv5_RUNS_DETECT_DIR')


# ========== DATASETS ==========

# -- MS-CXR --
MS_CXR_LOCAL_ALIGNMENT_CSV_PATH = os.getenv("MS_CXR_LOCAL_ALIGNMENT_V1.1.0_CSV_PATH")
raise_warning_if_none(MS_CXR_LOCAL_ALIGNMENT_CSV_PATH, "MS_CXR_LOCAL_ALIGNMENT_CSV_PATH")

# -- MIMIC-CXR --
MIMICCXR_DATASET_DIR = os.getenv('MIMICCXR_DATASET_DIR')
raise_error_if_none(MIMICCXR_DATASET_DIR, "MIMICCXR_DATASET_DIR")

MIMICCXR_JPG_IMAGES_SMALL_DIR = os.getenv('MIMICCXR_JPG_IMAGES_SMALL_DIR')
raise_error_if_none(MIMICCXR_JPG_IMAGES_SMALL_DIR, "MIMICCXR_JPG_IMAGES_SMALL_DIR")

MIMICCXR_JPG_IMAGES_MEDIUM_DIR = os.getenv('MIMICCXR_JPG_IMAGES_MEDIUM_DIR')
raise_error_if_none(MIMICCXR_JPG_IMAGES_MEDIUM_DIR, "MIMICCXR_JPG_IMAGES_MEDIUM_DIR")

MIMICCXR_JPG_IMAGES_LARGE_DIR = os.getenv('MIMICCXR_JPG_IMAGES_LARGE_DIR')
raise_error_if_none(MIMICCXR_JPG_IMAGES_LARGE_DIR, "MIMICCXR_JPG_IMAGES_LARGE_DIR")

MIMICCXR_JPG_DIR = os.getenv('MIMICCXR_JPG_DIR')
raise_error_if_none(MIMICCXR_JPG_DIR, "MIMICCXR_JPG_DIR")

MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_1_PATH = os.getenv('MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_1_PATH')
raise_warning_if_none(MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_1_PATH, "MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_1_PATH")

MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_2_PATH = os.getenv('MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_2_PATH')
raise_warning_if_none(MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_2_PATH, "MIMICCXR_CUSTOM_RADIOLOGIST_ANNOTATIONS_CSV_2_PATH")

MIMICCXR_METADATA_CSV_PATH = os.path.join(MIMICCXR_JPG_DIR, 'mimic-cxr-2.0.0-metadata.csv')
MIMICCXR_SPLIT_CSV_PATH = os.path.join(MIMICCXR_JPG_DIR, 'mimic-cxr-2.0.0-split.csv')
MIMICCXR_CACHE_DIR = os.path.join(CACHE_DIR, 'mimiccxr')
MIMICCXR_REPORTS_TXT_PATHS = os.path.join(MIMICCXR_CACHE_DIR, 'reports_txt_paths.pkl')
MIMICCXR_PATH_TO_REPORT_TEXT_DICT_PATH = os.path.join(MIMICCXR_CACHE_DIR, 'path_to_report_text_dict.pkl')

MIMICCXR_BACKGROUND_FINDINGS_AND_IMPRESSION_JSON_PATH = os.getenv(
    'MIMICCXR_BACKGROUND_FINDINGS_AND_IMPRESSION_JSON_PATH'
)
raise_warning_if_none(
    MIMICCXR_BACKGROUND_FINDINGS_AND_IMPRESSION_JSON_PATH,
    "MIMICCXR_BACKGROUND_FINDINGS_AND_IMPRESSION_JSON_PATH",
)

# -- MIMIC-CXR-LT 2023 --
MIMIC_CXR_LT_2023_TRAIN_CSV_PATH = os.getenv('MIMIC_CXR_LT_2023_TRAIN_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2023_TRAIN_CSV_PATH, "MIMIC_CXR_LT_2023_TRAIN_CSV_PATH")

MIMIC_CXR_LT_2023_DEV_CSV_PATH = os.getenv('MIMIC_CXR_LT_2023_DEV_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2023_DEV_CSV_PATH, "MIMIC_CXR_LT_2023_DEV_CSV_PATH")

MIMIC_CXR_LT_2023_TEST_CSV_PATH = os.getenv('MIMIC_CXR_LT_2023_TEST_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2023_TEST_CSV_PATH, "MIMIC_CXR_LT_2023_TEST_CSV_PATH")

# -- MIMIC-CXR-LT 2024 --
MIMIC_CXR_LT_2024_TASK1_TRAIN_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK1_TRAIN_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK1_TRAIN_CSV_PATH, "MIMIC_CXR_LT_2024_TASK1_TRAIN_CSV_PATH")

MIMIC_CXR_LT_2024_TASK1_DEV_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK1_DEV_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK1_DEV_CSV_PATH, "MIMIC_CXR_LT_2024_TASK1_DEV_CSV_PATH")

MIMIC_CXR_LT_2024_TASK1_TEST_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK1_TEST_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK1_TEST_CSV_PATH, "MIMIC_CXR_LT_2024_TASK1_TEST_CSV_PATH")

MIMIC_CXR_LT_2024_TASK2_TEST_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK2_TEST_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK2_TEST_CSV_PATH, "MIMIC_CXR_LT_2024_TASK2_TEST_CSV_PATH")

MIMIC_CXR_LT_2024_TASK3_TEST_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK3_TEST_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK3_TEST_CSV_PATH, "MIMIC_CXR_LT_2024_TASK3_TEST_CSV_PATH")

MIMIC_CXR_LT_2024_TASK1_EVAL_CLASSES_TXT_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK1_EVAL_CLASSES_TXT_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK1_EVAL_CLASSES_TXT_PATH, "MIMIC_CXR_LT_2024_TASK1_EVAL_CLASSES_TXT_PATH")

MIMIC_CXR_LT_2024_TASK2_EVAL_CLASSES_TXT_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK2_EVAL_CLASSES_TXT_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK2_EVAL_CLASSES_TXT_PATH, "MIMIC_CXR_LT_2024_TASK2_EVAL_CLASSES_TXT_PATH")

MIMIC_CXR_LT_2024_TASK3_EVAL_CLASSES_TXT_PATH = os.getenv('MIMIC_CXR_LT_2024_TASK3_EVAL_CLASSES_TXT_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_TASK3_EVAL_CLASSES_TXT_PATH, "MIMIC_CXR_LT_2024_TASK3_EVAL_CLASSES_TXT_PATH")

MIMIC_CXR_LT_2024_LABELS_CSV_PATH = os.getenv('MIMIC_CXR_LT_2024_LABELS_CSV_PATH')
raise_warning_if_none(MIMIC_CXR_LT_2024_LABELS_CSV_PATH, "MIMIC_CXR_LT_2024_LABELS_CSV_PATH")


# -- PADCHEST --

PADCHEST_DATASET_DIR = os.getenv('PADCHEST_DATASET_DIR')
raise_error_if_none(PADCHEST_DATASET_DIR, "PADCHEST_DATASET_DIR")

PADCHEST_IMAGES_SMALL_DIR = os.getenv('PADCHEST_IMAGES_SMALL_DIR')
raise_error_if_none(PADCHEST_IMAGES_SMALL_DIR, "PADCHEST_IMAGES_SMALL_DIR")

PADCHEST_GR_GROUNDED_REPORTS_JSON_PATH = os.getenv('PADCHEST_GR_GROUNDED_REPORTS_JSON_PATH')
raise_warning_if_none(PADCHEST_GR_GROUNDED_REPORTS_JSON_PATH, "PADCHEST_GR_GROUNDED_REPORTS_JSON_PATH")

PADCHEST_GR_MASTER_TABLE_CSV_PATH = os.getenv('PADCHEST_GR_MASTER_TABLE_CSV_PATH')
raise_warning_if_none(PADCHEST_GR_MASTER_TABLE_CSV_PATH, "PADCHEST_GR_MASTER_TABLE_CSV_PATH")

PADCHEST_GR_JPG_DIR = os.getenv('PADCHEST_GR_JPG_DIR')
raise_error_if_none(PADCHEST_GR_JPG_DIR, "PADCHEST_GR_JPG_DIR")

PADCHEST_CACHE_DIR = os.path.join(CACHE_DIR, 'padchest')
PADCHEST_LABELS_CSV_PATH = os.path.join(PADCHEST_DATASET_DIR, 'PADCHEST_chest_x_ray_images_labels_160K_01.02.19.csv')
PADCHEST_BROKEN_IMAGES_TXT_PATH = os.path.join(PADCHEST_CACHE_DIR, 'broken_images.txt')

# -- CHEST-IMAGENOME --

CHEST_IMAGENOME_SILVER_SCENE_GRAPHS_DIR = os.getenv('CHEST_IMAGENOME_SILVER_SCENE_GRAPHS_DIR')
raise_warning_if_none(CHEST_IMAGENOME_SILVER_SCENE_GRAPHS_DIR, "CHEST_IMAGENOME_SILVER_SCENE_GRAPHS_DIR")

CHEST_IMAGENOME_SILVER_DATASET_DIR = os.getenv('CHEST_IMAGENOME_SILVER_DATASET_DIR')
raise_warning_if_none(CHEST_IMAGENOME_SILVER_DATASET_DIR, "CHEST_IMAGENOME_SILVER_DATASET_DIR")

CHEST_IMAGENOME_IMAGES_TO_AVOID_CSV_PATH = os.getenv('CHEST_IMAGENOME_IMAGES_TO_AVOID_CSV_PATH')
raise_warning_if_none(CHEST_IMAGENOME_IMAGES_TO_AVOID_CSV_PATH, "CHEST_IMAGENOME_IMAGES_TO_AVOID_CSV_PATH")

CHEST_IMAGENOME_GOLD_BBOX_COORDINATE_ANNOTATIONS_CSV_PATH = os.getenv('CHEST_IMAGENOME_GOLD_BBOX_COORDINATE_ANNOTATIONS_CSV_PATH')
raise_warning_if_none(CHEST_IMAGENOME_GOLD_BBOX_COORDINATE_ANNOTATIONS_CSV_PATH, "CHEST_IMAGENOME_GOLD_BBOX_COORDINATE_ANNOTATIONS_CSV_PATH")

CHEST_IMAGENOME_GOLD_ATTRIBUTE_RELATIONS_TXT_PATH = os.getenv('CHEST_IMAGENOME_GOLD_ATTRIBUTE_RELATIONS_TXT_PATH')
raise_warning_if_none(CHEST_IMAGENOME_GOLD_ATTRIBUTE_RELATIONS_TXT_PATH, "CHEST_IMAGENOME_GOLD_ATTRIBUTE_RELATIONS_TXT_PATH")

CHEST_IMAGENOME_YOLOV5_LABELS_DIR = os.getenv('CHEST_IMAGENOME_YOLOV5_LABELS_DIR')
raise_warning_if_none(CHEST_IMAGENOME_YOLOV5_LABELS_DIR, "CHEST_IMAGENOME_YOLOV5_LABELS_DIR")

CHEST_IMAGENOME_CACHE_DIR = os.path.join(CACHE_DIR, 'chest_imagenome')
CHEST_IMAGENOME_SILVER_BBOXES_FILEPATH = os.path.join(CHEST_IMAGENOME_CACHE_DIR, 'bboxes.pkl')
CHEST_IMAGENOME_HORIZONTALLY_FLIPPED_SILVER_BBOXES_FILEPATH = os.path.join(CHEST_IMAGENOME_CACHE_DIR, 'horizontally_flipped_bboxes.pkl')

# -- CHEXLOCALIZE --

CHEXLOCALIZE_DATA_DIR = os.getenv('CHEXLOCALIZE_DATA_DIR')
raise_error_if_none(CHEXLOCALIZE_DATA_DIR, "CHEXLOCALIZE_DATA_DIR")

CHEXLOCALIZE_WORKSPACE_DIR = os.getenv('CHEXLOCALIZE_WORKSPACE_DIR')
raise_error_if_none(CHEXLOCALIZE_WORKSPACE_DIR, "CHEXLOCALIZE_WORKSPACE_DIR")

CHEXLOCALIZE_CHEXPERT_TEST_LABELS_CSV_PATH = os.getenv('CHEXLOCALIZE_CHEXPERT_TEST_LABELS_CSV_PATH')
raise_warning_if_none(CHEXLOCALIZE_CHEXPERT_TEST_LABELS_CSV_PATH, "CHEXLOCALIZE_CHEXPERT_TEST_LABELS_CSV_PATH")

CHEXLOCALIZE_CHEXPERT_VAL_LABELS_CSV_PATH = os.getenv('CHEXLOCALIZE_CHEXPERT_VAL_LABELS_CSV_PATH')
raise_warning_if_none(CHEXLOCALIZE_CHEXPERT_VAL_LABELS_CSV_PATH, "CHEXLOCALIZE_CHEXPERT_VAL_LABELS_CSV_PATH")

CHEXLOCALIZE_TEST_GT_ANNOTATIONS_JSON_PATH = os.getenv('CHEXLOCALIZE_TEST_GT_ANNOTATIONS_JSON_PATH')
raise_warning_if_none(CHEXLOCALIZE_TEST_GT_ANNOTATIONS_JSON_PATH, "CHEXLOCALIZE_TEST_GT_ANNOTATIONS_JSON_PATH")

CHEXLOCALIZE_VAL_GT_ANNOTATIONS_JSON_PATH = os.getenv('CHEXLOCALIZE_VAL_GT_ANNOTATIONS_JSON_PATH')
raise_warning_if_none(CHEXLOCALIZE_VAL_GT_ANNOTATIONS_JSON_PATH, "CHEXLOCALIZE_VAL_GT_ANNOTATIONS_JSON_PATH")

CHEXLOCALIZE_IMAGE_DIR_512X512 = os.path.join(CHEXLOCALIZE_WORKSPACE_DIR, 'CheXpert_512x512')
raise_error_if_none(CHEXLOCALIZE_IMAGE_DIR_512X512, "CHEXLOCALIZE_IMAGE_DIR_512X512")

CHEXLOCALIZE_CACHE_DIR = os.path.join(CACHE_DIR, 'chexlocalize')

# -- CHEXPERT --

CHEXPERT_DATASET_DIR = os.getenv('CHEXPERT_DATASET_DIR')
raise_error_if_none(CHEXPERT_DATASET_DIR, "CHEXPERT_DATASET_DIR")

CHEXPERT_V1_0_SMALL_DATASET_DIR = os.getenv('CHEXPERT_V1.0_SMALL_DATASET_DIR')
raise_error_if_none(CHEXPERT_V1_0_SMALL_DATASET_DIR, "CHEXPERT_V1.0_SMALL_DATASET_DIR")

CHEXPERT_DATASET_AUX_DIR = os.getenv('CHEXPERT_DATASET_AUX_DIR')
raise_error_if_none(CHEXPERT_DATASET_AUX_DIR, "CHEXPERT_DATASET_AUX_DIR")

CHEXPERT_PLUS_CSV_PATH = os.getenv('CHEXPERT_PLUS_CSV_PATH')
raise_warning_if_none(CHEXPERT_PLUS_CSV_PATH, "CHEXPERT_PLUS_CSV_PATH")

CHEXPERT_CACHE_DIR = os.path.join(CACHE_DIR, 'chexpert')
CHEXPERT_TRAIN_CSV_PATH = os.path.join(CHEXPERT_DATASET_DIR, 'CheXpert-v1.0-small', 'train.csv')
CHEXPERT_VALID_CSV_PATH = os.path.join(CHEXPERT_DATASET_DIR, 'CheXpert-v1.0-small', 'valid.csv')
CHEXPERT_TRAIN_VISUALCHEXBERT_CSV_PATH = os.path.join(CHEXPERT_DATASET_DIR, 'CheXpert-v1.0-small', 'train_visualCheXbert.csv')
CHEXPERT_TRAIN_VAL_CSV_PATH = os.path.join(CHEXPERT_DATASET_DIR, 'CheXpert-v1.0-small', 'train-val.csv')
CHEXPERT_TEST_LABELS_CSV_PATH = os.path.join(CHEXPERT_DATASET_DIR, 'CheXpert-v1.0-small', 'test_labels.csv')

# -- IUXRAY --

IUXRAY_DATASET_DIR = os.getenv('IUXRAY_DATASET_DIR')
raise_error_if_none(IUXRAY_DATASET_DIR, "IUXRAY_DATASET_DIR")

IUXRAY_IMAGE_INFO_JSON_PATH = os.path.join(IUXRAY_DATASET_DIR, 'info.json')
IUXRAY_REPORTS_JSON_PATH = os.path.join(IUXRAY_DATASET_DIR, 'reports/reports.json')
IUXRAY_REPORTS_MIN_JSON_PATH = os.path.join(IUXRAY_DATASET_DIR, 'reports/reports.min.json')
IUXRAY_CACHE_DIR = os.path.join(CACHE_DIR, 'iuxray')

# -- VINBIG --

# # VINBIG_ORIGINAL_IMAGES_FOLDER = os.environ['VINBIG_ORIGINAL_IMAGES_FOLDER']
# # VINBIG_512x512_IMAGES_FOLDER = os.environ['VINBIG_512x512_IMAGES_FOLDER']

VINBIG_ORIGINAL_IMAGES_FOLDER = os.getenv('VINBIG_ORIGINAL_HQ_IMAGES_FOLDER')
raise_error_if_none(VINBIG_ORIGINAL_IMAGES_FOLDER, "VINBIG_ORIGINAL_HQ_IMAGES_FOLDER")

VINBIG_512x512_IMAGES_FOLDER = os.getenv('VINBIG_512x512_HQ_IMAGES_FOLDER')
raise_error_if_none(VINBIG_512x512_IMAGES_FOLDER, "VINBIG_512x512_HQ_IMAGES_FOLDER")

VINBIG_ALL_IMAGES_TXT_PATH = os.getenv('VINBIG_ALL_IMAGES_TXT_PATH')
raise_warning_if_none(VINBIG_ALL_IMAGES_TXT_PATH, "VINBIG_ALL_IMAGES_TXT_PATH")

VINBIG_TRAIN_VAL_IMAGES_TXT_PATH = os.getenv('VINBIG_TRAIN_VAL_IMAGES_TXT_PATH')
raise_warning_if_none(VINBIG_TRAIN_VAL_IMAGES_TXT_PATH, "VINBIG_TRAIN_VAL_IMAGES_TXT_PATH")

VINBIG_TEST_IMAGES_TXT_PATH = os.getenv('VINBIG_TEST_IMAGES_TXT_PATH')
raise_warning_if_none(VINBIG_TEST_IMAGES_TXT_PATH, "VINBIG_TEST_IMAGES_TXT_PATH")

VINBIG_LABELS_CSV_PATH = os.getenv('VINBIG_LABELS_CSV_PATH')
raise_warning_if_none(VINBIG_LABELS_CSV_PATH, "VINBIG_LABELS_CSV_PATH")

VINBIG_IMAGE_LABELS_TRAIN_CSV_PATH = os.getenv('VINBIG_IMAGE_LABELS_TRAIN_CSV_PATH')
raise_warning_if_none(VINBIG_IMAGE_LABELS_TRAIN_CSV_PATH, "VINBIG_IMAGE_LABELS_TRAIN_CSV_PATH")

VINBIG_IMAGE_LABELS_TEST_CSV_PATH = os.getenv('VINBIG_IMAGE_LABELS_TEST_CSV_PATH')
raise_warning_if_none(VINBIG_IMAGE_LABELS_TEST_CSV_PATH, "VINBIG_IMAGE_LABELS_TEST_CSV_PATH")

VINBIG_ANNOTATIONS_TRAIN_CSV_PATH = os.getenv('VINBIG_ANNOTATIONS_TRAIN_CSV_PATH')
raise_warning_if_none(VINBIG_ANNOTATIONS_TRAIN_CSV_PATH, "VINBIG_ANNOTATIONS_TRAIN_CSV_PATH")

VINBIG_ANNOTATIONS_TEST_CSV_PATH = os.getenv('VINBIG_ANNOTATIONS_TEST_CSV_PATH')
raise_warning_if_none(VINBIG_ANNOTATIONS_TEST_CSV_PATH, "VINBIG_ANNOTATIONS_TEST_CSV_PATH")

VINBIG_YOLOV5_LABELS_DIR = os.getenv('VINBIG_YOLOV5_LABELS_DIR')
raise_warning_if_none(VINBIG_YOLOV5_LABELS_DIR, "VINBIG_YOLOV5_LABELS_DIR")

VINBIG_CACHE_DIR = os.path.join(CACHE_DIR, 'vinbig')

# -- ReXGradient-160K --
REXGRADIENT_160K_DATASET_DIR = os.getenv('REXGRADIENT_160K_DATASET_DIR')
raise_error_if_none(REXGRADIENT_160K_DATASET_DIR, "REXGRADIENT_160K_DATASET_DIR")

REXGRADIENT_160K_TRAIN_METADATA_CSV_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'train_metadata.csv')
REXGRADIENT_160K_TRAIN_METADATA_JSON_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'train_metadata.json')
REXGRADIENT_160K_VAL_METADATA_CSV_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'valid_metadata.csv')
REXGRADIENT_160K_VAL_METADATA_JSON_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'valid_metadata.json')
REXGRADIENT_160K_TEST_METADATA_CSV_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'test_metadata.csv')
REXGRADIENT_160K_TEST_METADATA_JSON_PATH = os.path.join(REXGRADIENT_160K_DATASET_DIR, 'test_metadata.json')
REXGRADIENT_160K_LARGE_FAST_CACHE_DIR = os.path.join(LARGE_FAST_CACHE_DIR, 'rexgradient_160k')
REXGRADIENT_160K_FAST_CACHE_DIR = os.path.join(FAST_CACHE_DIR, 'rexgradient_160k')
REXGRADIENT_160K_FAST_TMP_DIR = os.path.join(FAST_TMP_DIR, 'rexgradient_160k')